# .swiftlint.yml
# SwiftLint configuration for BidoneDemo
# MVI Architecture · SwiftUI · iOS 17+

# ─── Paths ───────────────────────────────────────────────
excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage
  - BidoneDemoUITests/SnapshotHelper.swift

# ─── Disabled Rules ─────────────────────────────────────
disabled_rules:
  - trailing_whitespace
  - todo
  - type_name
  # Disabled globally because violations only occur in test targets
  # (XCTest patterns like `app!` and `data(using:)!`)
  # and these rules don't support per-path exclusion.
  - force_unwrapping
  - implicitly_unwrapped_optional

# ─── Opt-in Rules ───────────────────────────────────────
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - last_where
  - legacy_multiple
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - yoda_condition

# ─── Rule Configuration ────────────────────────────────

line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - i
    - id
    - x
    - y
    - n

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 3
    error: 5

large_tuple:
  warning: 3
  error: 4

enum_case_associated_values_count:
  warning: 5
  error: 6

vertical_whitespace:
  max_empty_lines: 2

reporter: xcode
