# fastlane/Snapfile

devices([
  "iPhone 17 Pro",
  "iPad Pro 13-inch (M5)"
])

languages([
  "en-US"
])

project "./BidoneDemo.xcodeproj"
scheme "BidoneDemo"
output_directory "./fastlane/screenshots"
clear_previous_screenshots(true)
stop_after_first_error(true)
override_status_bar(true)
erase_simulator(true)
concurrent_simulators(false)

# Only run snapshot tests, skip unit tests and other UI tests
xcargs "'-parallel-testing-enabled' 'NO' '-only-testing:BidoneDemoUITests/SnapshotTests'"